import { returnsRepository } from '../../modules/returns/returns.repository.js';
import { assertValidTransition } from '../../modules/returns/returns.state-machine.js';
import { logger } from '../../lib/logger.js';

/**
 * Step Functions Task 4: UpdateStatus (§1.6)
 * Transitions return state to LABEL_GENERATED and records audit timeline.
 *
 * @param {object} event - Output from UploadToS3
 * @returns {Promise<object>} - Updated return payload for SNS notification
 */
export const handler = async (event) => {
  const { returnId, returnNumber, trackingNumber, labelKey, carrier } = event;

  logger.info({ returnNumber, labelKey }, 'Step Functions: Advancing status to LABEL_GENERATED');

  try {
    const returnDoc = await returnsRepository.findById(returnId);
    if (returnDoc) {
      assertValidTransition(returnDoc.status, 'LABEL_GENERATED');

      await returnsRepository.updateStatus(
        returnId,
        'LABEL_GENERATED',
        {
          labelKey,
          trackingNumber,
          carrier: carrier || 'UPS',
        },
        {
          status: 'LABEL_GENERATED',
          timestamp: new Date(),
          note: `Pre-paid shipping label generated by Step Functions (${carrier}: ${trackingNumber})`,
          actor: 'STEP_FUNCTIONS_LAMBDA',
        }
      );
    }
  } catch (err) {
    logger.warn({ error: err.message, returnNumber }, 'Database status update failed or skipped in local mock');
  }

  return {
    returnId,
    returnNumber,
    status: 'LABEL_GENERATED',
    trackingNumber,
    labelKey,
    carrier: carrier || 'UPS',
    completedAt: new Date().toISOString(),
    event: 'LABEL_READY',
  };
};
